services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      # se quiser HTTPS local com mkcert, dá pra expor 443 e configurar depois
      # - "443:443"
    depends_on:
      - frontend
      - strapi
    networks: [strapi]

  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    command: sh -c "npm run develop"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 1337
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: mysql
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      # Opcional: ajuda Strapi a gerar URLs absolutas corretas
      # STRAPI_URL: http://dominio.local
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./public/uploads:/opt/app/public/uploads
      - ./.env:/opt/app/.env
      - ./package.json:/opt/app/package.json
    ports:
      - "1337:1337"
    networks: [strapi]
    depends_on: [mysql]

  frontend:
    build: ./src/frontend
    container_name: frontend
    working_dir: /app
    volumes:
      - ./src/frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks: [strapi]

  mysql:
    container_name: mysql
    platform: linux/amd64
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks: [strapi]

volumes:
  strapi-data:

networks:
  strapi:
    name: strapi
    driver: bridge
