services:
  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    command: sh -c "npm run develop"              # <- dev
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 1337
      VITE_HOST: 0.0.0.0                          # <- faz o Vite bindar
      VITE_PORT: 5173
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: mysql
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./public/uploads:/opt/app/public/uploads
      - ./.env:/opt/app/.env
      - ./package.json:/opt/app/package.json      # <- mapeie dentro de /opt/app
      # (se usar lock): - ./package-lock.json:/opt/app/package-lock.json
    ports:
      - "1337:1337"
      - "5173:5173"                               # <- EXPOSE Vite
    networks: [strapi]
    depends_on: [mysql]

  frontend:
    build: ./src/frontend
    container_name: frontend
    working_dir: /app
    volumes:
      - ./src/frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks: [strapi]

  mysql:
    container_name: mysql
    platform: linux/amd64
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks: [strapi]

volumes:
  strapi-data:

networks:
  strapi:
    name: strapi
    driver: bridge
